spring.application.name=search-api

# --- DB 接続設定（Render の新しい Postgres） ---
spring.datasource.url=jdbc:postgresql://dpg-d70dosvkijhs73db4gh0-a:5432/my_app_db_k40s
spring.datasource.username=my_app_db_k40s_user
spring.datasource.password=kufzTkXz8fx6tX5oJVvr2BiR0k0peIIJ
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA 設定 ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- ログ ---
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
